package com.api.xpress.gateways;

import com.api.xpress.agreement.data.model.LoanAgreement;
import com.api.xpress.auth.security.user.AuthenticatedUser;
import com.api.xpress.auth.security.user.CurrentUser;
import com.api.xpress.auth.security.utility.AuthenticationToken;
import com.api.xpress.loan.data.models.Loan;
import com.api.xpress.loan.data.models.LoanStatus;
import com.api.xpress.loan_officer.data.dto.request.AgreementRequest;
import com.api.xpress.loan_officer.data.dto.request.InviteRequest;
import com.api.xpress.loan_officer.data.dto.request.OfficerRequest;
import com.api.xpress.loan_officer.data.dto.request.UpdateLoanRequest;
import com.api.xpress.loan_officer.data.models.LoanOfficer;
import com.api.xpress.loan_officer.services.LoanOfficerService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import lombok.RequiredArgsConstructor;
import org.springdoc.core.annotations.ParameterObject;
import org.springframework.data.domain.Page;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.web.bind.annotation.*;

import static org.springframework.http.MediaType.MULTIPART_FORM_DATA_VALUE;


@RestController
@RequiredArgsConstructor
@RequestMapping("/api/v1/officer")
@Tag(name = "Loan Officer Controller")
public class LoanOfficerController {
    private final LoanOfficerService loanOfficerService;

    @PostMapping("/invite")
    @Operation(summary = "Invite Loan Officer")
    public ResponseEntity<String> inviteLoanOfficer(@RequestBody @Valid InviteRequest request) {

        return ResponseEntity.ok(loanOfficerService.inviteAdmin(request));
    }

    @PostMapping(value = "/update", consumes = MULTIPART_FORM_DATA_VALUE)
    @Operation(summary = "Update Loan Officer profile")
    public ResponseEntity<AuthenticationToken> updateLoanOfficer(@ModelAttribute @Valid OfficerRequest request) {

        return ResponseEntity.ok(loanOfficerService.completeOfficerProfile(request));
    }

    @PostMapping("/update_loan")
    @PreAuthorize("hasAuthority('LOAN_OFFICER')")
    @Operation(summary = "Update the status of a loan application")
    public ResponseEntity<LoanStatus> updateLoanStatus(@RequestBody @Valid UpdateLoanRequest request) {

        return ResponseEntity.ok(loanOfficerService.updateLoanStatus(request));
    }

    @GetMapping("/fresh")
    @PreAuthorize("hasAuthority('LOAN_OFFICER')")
    @Operation(summary = "Pending applications")
    public ResponseEntity<Page<Loan>> fresh(@ParameterObject int pageNumber) {

        return ResponseEntity.ok(loanOfficerService.allFreshLoans(pageNumber));
    }

    @GetMapping("/current")
    @PreAuthorize("hasAuthority('LOAN_OFFICER')")
    @Operation(summary = "Get current loan officer")
    public ResponseEntity<LoanOfficer> currentLoanOfficer(@CurrentUser AuthenticatedUser currentUser) {

        return ResponseEntity.ok(loanOfficerService.currentLoanOfficer(currentUser));
    }

    @PostMapping("/approve")
    @PreAuthorize("hasAuthority('LOAN_OFFICER')")
    @Operation(summary = "To approve a loan application")
    public ResponseEntity<LoanStatus> approveLoanApplication(@ParameterObject Long loanId) {

        return ResponseEntity.ok(loanOfficerService.approveLoanApplication(loanId));
    }

    @PostMapping("/reject")
    @PreAuthorize("hasAuthority('LOAN_OFFICER')")
    @Operation(summary = "To reject a loan application")
    public ResponseEntity<LoanStatus> rejectLoanApplication(@ParameterObject Long loanId) {

        return ResponseEntity.ok(loanOfficerService.rejectLoanApplication(loanId));
    }

    @PostMapping("/agreement")
    @PreAuthorize("hasAuthority('LOAN_OFFICER')")
    @Operation(summary = "To generate a loan agreement")
    public ResponseEntity<LoanAgreement> generateAgreement(@RequestBody @Valid AgreementRequest request, @CurrentUser AuthenticatedUser currentUser) {

        return ResponseEntity.ok(loanOfficerService.generateAgreement(request, currentUser));
    }

    @GetMapping("/agreements")
    @PreAuthorize("hasAuthority('LOAN_OFFICER')")
    @Operation(summary = "all loan agreements generated by a loan officer")
    public ResponseEntity<Page<LoanAgreement>> allLoanAgreementsByAnOfficer(@ParameterObject int pageNumber, @CurrentUser AuthenticatedUser currentUser) {

        return ResponseEntity.ok(loanOfficerService.allLoanAgreementByOfficerId(pageNumber, currentUser));
    }
}