spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    filter: true
    tagsSorter: alpha

sendinblue:
  mail:
    api_key: ${sendinblue_api}
    url: ${sendinblue_mail}
app:
  name: ${app_name}
  email: ${app_email}

access_expiration: ${access_token}
refresh_expiration: ${refresh_token}


cloudinary_name: ${cloud_name}
cloudinary_api_key: ${cloud_key}
cloudinary_api_secret: ${cloud_secret}

Jwt_Secret_Key: ${SECRET_KEY}