spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:xpress}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 2
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
  profiles:
    active: dev
springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    filter: true
    tags-sorter: alpha
    operations-sorter: alpha
    doc-expansion: none
    deep-linking: true
    display-request-duration: true
    default-models-expand-depth: 1
    default-model-rendering: example
    show-extensions: true
    display-operation-id: false
    persist-authorization: true
    try-it-out-enabled: true
server:
  port: 8080

sendinblue:
  mail:
    api_key: ${BREVO_API_KEY:your_brevo_api_key_here}
    url: ${MAIL_URL:https://api.brevo.com/v3/smtp/email}

app:
  name: ${APP_NAME:Xpress}
  email: ${APP_EMAIL:oneblockhq@gmail.com}

token:
  secret: ${SECRET_KEY:OIDCu9SZ9U5LGqF6mW12KxLuSxO70GPfqw3W2fh4uciXEi17bxij7229eNsVXRZnpsOa7pMb8gGbfJdl8YmnZ5uuaA43RPRH1v8720TWYUwAST90hzdLdzVYh54WXm44}
  expiration:
    access: ${ACCESS_TOKEN_EXP:3}
    refresh: ${REFRESH_TOKEN_EXP:168}


cloudinary:
  name: ${CLOUDINARY_NAME:ddgm9zdnr}
  api_key: ${CLOUDINARY_KEY:249119262672761}
  api_secret: ${CLOUDINARY_SECRET:IGsVcz3MwMDrUmd-kyahxGL-x1Y}