DB_HOST: localhost
DB_NAME: hero_db
DB_USERNAME: postgres
DB_PASSWORD: "@Tiptop2059!"
DB_PORT : 5432
DATABASE: postgresql
DIALECT : org.hibernate.dialect.PostgreSQLDialect

SECRET_KEY: OIDCu9SZ9U5LGqF6mW12K LuSxO70GPfqw3W2fh4uciXEi17bxij7229eNsVXRZnpsOa7pMb8gGbfJdl8YmnZ5uuaA43RPRH1v8720TWYUwAST90hzdLdzVYh54WXm44


sendinblue_mail: https://api.sendinblue.com/v3/smtp/email

app_name: Hero Money
app_email: info@heromoney.com

cloud_name: ddgm9zdnr
cloud_secret: IGsVcz3MwMDrUmd-kyahxGL-x1Y
cloud_key: 249119262672761

# 3 hours
access_token: 10800
# 1 week
refresh_token: 604800















#Render env variables
#DB_HOST: containers-us-west-104.railway.app
#DB_NAME: railway
#DB_USERNAME: postgres
#DB_PASSWORD: jTFqjXXin8sZKU9cKvK6
#DB_PORT : 8062
#DATABASE: postgresql
#DIALECT : org.hibernate.dialect.PostgreSQLDialect
#
#SECRET_KEY: OIDCu9SZ9U5LGqF6mW12K LuSxO70GPfqw3W2fh4uciXEi17bxij7229eNsVXRZnpsOa7pMb8gGbfJdl8YmnZ5uuaA43RPRH1v8720TWYUwAST90hzdLdzVYh54WXm44
#
#sendinblue_api: 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
#sendinblue_mail: https://api.sendinblue.com/v3/smtp/email
#
#app_name: Hero Money
#app_email: info@heromoney.com
#
#cloud_name: ddgm9zdnr
#cloud_secret: IGsVcz3MwMDrUmd-kyahxGL-x1Y
#cloud_key: 249119262672761
#
## 3 hours
#access_token: 10800
## 1 week
#refresh_token: 604800